### ISSUE TITLE
Disable HTML Minify (feature) ?

### ISSUE THREAD

**Issue by spAnser** [tssajo/Minify#27] opened 2015-06-19 20:25 UTC
I like the auto minify on save option. I just wish I could disable it for html while keeping css and javascript minify.

**Comment by tssajo** [comment] 2015-06-19 21:03
@spAnser It's a good idea, but hard to implement... When I find time to do it, I might do it. Don't expect it to be implemented anytime soon.

**Comment by spAnser** [comment] 2015-06-19 21:05
That is fine I just didn't know of an easier way to contact you.

**Comment by tssajo** [comment] 2015-06-19 21:07
@spAnser I prefer to be contacted about `Minify` here on GitHub, so you did perfectly fine.

**Comment by SavageCore** [comment] 2015-07-03 20:21
@spAnser 
What do you think of this? Would you prefer manual minify always works and only block on save? 
Right now I just prevented any non listed file type from working in either scenario.

**Comment by spAnser** [comment] 2015-07-03 20:53
Looks good. Will check it out later

**Comment by tssajo** [comment] 2015-07-16 15:41
@SavageCore ,  @spAnser

Hey Guys,

So how stable is this patch? Is it working perfectly for you both? Is it ready to be merged?
Please advise and I'll merge when you say it's 100% stable.

Thanks!

**Comment by spAnser** [comment] 2015-07-16 16:06
I haven't had any crashing issues using it. He did however block minify triggered via command as well. I wouldn't mind having minify via command always available to whatever and just blocking the auto minify.

**Comment by SavageCore** [comment] 2015-07-16 17:20
Yup no problems here. 

@spAnser I think you're right and command should always work. So @tssajo perhaps wait till I get that change done.

**Comment by tssajo** [comment] 2015-07-16 17:26
Okay, thanks guys!

@SavageCore I really appreciate your contribution! I haven't tested (ran) your PR yet, but I looked at your changes at the source code level and I like it. Seems to be clean and should work as intended.
Once you make that minor change about the manual command, I'll merge it and then bump the version of the plugin. Thanks!

**Comment by SavageCore** [comment] 2015-07-16 18:26
@tssajo @spAnser There we go! done and rebased

**Comment by tssajo** [comment] 2015-07-29 17:41
`Minify` v1.2.0 includes this feature.
@spAnser thanks for the suggestion!
@SavageCore Thanks for the implementation and the PR!

**Closed by tssajo** 2015-07-29 17:41 UTC
Labels: enhancement
