### ISSUE TITLE
keyboard shortcut not working

### ISSUE THREAD

**Issue by moxdev** [tssajo/Minify#36] opened 2015-10-26 13:36 UTC
Is there something you need to activate for the keyboard shortcut to work? Plugin works beautifully from the Tools > Minify > Minify File but can not get it to trigger using the shortcut provided in the README instruction. All dependencies are installed and plugin seems to be working fine its just the keyboard shortcut thats not working. Im running OSX 10.10.5.

**Comment by tssajo** [comment] 2015-10-26 13:52
@moxdev I don't know, primarily I use the plugin in Windows and the keyboard shortcuts work just fine. Maybe it's a problem related to a different keyboard layout on the Mac? E.g. you have keys there such as `Super` and `Cmd` and probably you need to use those instead of the standard `Ctrl` and `Alt` keys?? BTW, these are the key bindings for OS X :
```
[
  {"keys": ["super+alt+m"], "command": "minify"},
  {"keys": ["super+alt+shift+m"], "command": "beautify"}
]
```

**Comment by moxdev** [comment] 2015-10-26 14:20
Yeah I tried both of those key bindings but it does not trigger the minify. Not sure why not I dont have any conflicting key bindings or anything and even tried restarting. Ill keep looking into it. Other than that its a great plugin thanks for your hard work!

**Comment by tssajo** [comment] 2015-12-02 07:22
Since I could not reproduce this and nobody else is having this issue, I close it now.

But if you can add more info (e.g. if you find out what is causing this issue on your computer) then please feel free to add new comments.

**Closed by tssajo** 2015-12-02 07:22 UTC
