### ISSUE TITLE
Issue with cached ftp files

### ISSUE THREAD

**Issue by naymapl** [tssajo/Minify#53] opened 2017-03-02 09:51 UTC
Hi.

I have problem with css files imported via FTP. When I save if I always got issue message:

```
cleancss --s0 -s --skip-rebase -o /Users/....../Library/Caches/Transmit/style.min.css /Users/...../Library/Caches/Transmit/style.css

[31mERROR[39m: Ignoring local @import of "../Divi/style.css" as resource is missing.
```
Like you see I use function to skip @import (-s) but is still error with this. When i remove line from my css file:

"@import url('../Divi/style.css');"

everything working well. Any idea how to fix that ??

**Comment by tssajo** [comment] 2019-03-16 11:26
@naymapl Hey, sorry for the really late answer!

It seems to me that this was most likely caused by a bug in the [clean-css](https://github.com/jakubpawlowicz/clean-css) program. As you are probably aware, there are newer versions of `clean-css`. Have you tried to use a newer one via this CLI interface: [clean-css-cli](https://github.com/jakubpawlowicz/clean-css-cli) ?

Because I believe this was not caused by a bug in `Minify` itself, I am closing this Issue now.
However, feel free to add comments here if you have any additional information about this issue.

**Closed by tssajo** 2019-03-16 11:26 UTC
