### ISSUE TITLE
Fails to minify with uglifycss

### ISSUE THREAD

**Issue by ibrokemypie** [tssajo/Minify#61] opened 2017-08-28 03:12 UTC
uglifycss: unable to process ">"
	Error: ENOENT: no such file or directory, open '>'

works fine in terminal

**Comment by tssajo** [comment] 2019-03-16 12:24
@ibrokemypie Hey, sorry for answering this late!

It's really hard to tell what caused that. Maybe the file name of your CSS file had some special character(s) or spaces in it? It could also be caused by a permission issue: maybe you did not have write permission to the destination directory? With no further info, it is impossible to tell.

Anyhow, it is highly recommended to switch to the new [clean-css-cli](https://github.com/jakubpawlowicz/clean-css-cli) program for CSS file minification. This is well tested and works fine when using `Minify`.

Since this is such an old report with very little details and also because `uglifycss` program is not the preferred CSS minifier, I am closing this Issue now.
However, feel free to add any further comments here if you have additional information. Thanks!

**Closed by tssajo** 2019-03-16 12:24 UTC
